(ns leihs.core.icons
  (:refer-clojure :exclude [str keyword])
  (:require
    [leihs.core.core :refer [keyword str presence]]))

(def abort [:i.fas.fa-times-circle])
(def add [:i.fas.fa-plus-circle])
(def admin [:i.fas.fa-wrench])
(def api-token [:i.fas.fa-key])
(def api-tokens api-token)
(def delegation [:i.fas.fa-hands-helping])
(def delegations delegation)
(def delete [:i.fas.fa-times])
(def edit [:i.fas.fa-edit])
(def group [:i.fas.fa-users])
(def groups [:i.fas.fa-users])
(def home [:i.fas.fa-home])
(def me-user [:i.fas.fas-user])
(def sign-in [:i.fas.fa-sign-in-alt])
(def sign-out [:i.fas.fa-sign-out-alt])
(def user [:i.fas.fa-user])
(def users [:i.fas.fa-user-friends])
